import type { Metadata } from "next";
import  localFont from "next/font/local";
import "./globals.css";


const arad = localFont({
  src: "../public/font/AradVF.woff2",
  variable: "--font-arad",
  display: "swap",

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${arad.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
